## <center><b>Desafio 3 - Titanic - Aprendizado de Máquina a partir do Desastre</b></center>

### <b>ARQUIVOS e DATAFRAMES</b>
<ul>
    <li>train.csv -> Será usado para construir o modelo de aprendizado de máquina <br/>
    <li>test.csv -> Será usado para testar o modelo
</ul>

https://www.kaggle.com/competitions/titanic<br/><br/>
Data Cleaning Process -> https://www.youtube.com/watch?v=Y_s3hndYbB0&t=49s<br/>
EDA -> https://youtu.be/xLW796-J5fI?is=PnHRjUx7owx_0BFc

In [2]:
from pandas import read_csv

train = 'https://github.com/ajndantas/I2A2-Grupo_01/raw/refs/heads/master/Insurminds/Desafio%203/titanic/train.csv'
test = 'https://github.com/ajndantas/I2A2-Grupo_01/raw/refs/heads/master/Insurminds/Desafio%203/titanic/test.csv'

df_train = read_csv(train)
df_test = read_csv(test)

### <center><b>DATAFRAME DE TREINAMENTO</b></center>

### <b>ANÁLISE DOS DADOS</b>

In [3]:
df_train.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [4]:
df_train.tail(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### <b>DATA CLEANING</b>

<ul>
    <li><b>Detectando valores faltantes, tipos de dados, quantidade de linhas e colunas</b></li>
    <li><b>Normalizando os nomes das colunas</b></li>
    <li><b>Porcentagem de valores nulos</b></li>
    <li><b>Lidando com duplicatas, valores nulos e colunas bagunçadas (Padronizar colunas com valores categóricos)</b></li>
</ul>

<b>Detectando valores faltantes, tipos de dados, quantidade de linhas e colunas</b>

In [5]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

<b>Normalizando os nomes das colunas</b>
<ul>
    <li>Colocando tudo como minúscula</li>
    <li>Removendo espaços em branco</li>
    <li>Removendo parenteses (Não será necessário)</li>
</ul>

In [6]:
df_train.columns = (
                        df_train.columns.
                        str.lower().
                        str.strip()
                    )

df_train.columns

Index(['passengerid', 'survived', 'pclass', 'name', 'sex', 'age', 'sibsp',
       'parch', 'ticket', 'fare', 'cabin', 'embarked'],
      dtype='object')

<b>Porcentagem de valores nulos</b>

Se os dados tiverem mais do que 40% de valores nulos, eles devem ser checados/descartados

In [7]:
missing = ((df_train.isnull().sum() / len(df_train)) * 100)
missing[missing>0]

age         19.865320
cabin       77.104377
embarked     0.224467
dtype: float64

Descartando a coluna 'cabin'

In [8]:
df_train = df_train.drop(columns='cabin',axis=1,errors='ignore')
df_train

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

<b>Lidando com duplicatas, valores nulos e colunas bagunçadas (Padronizar colunas com valores categóricos)</b>

<ul>
    <li>Cheque a quantidade de duplicatas antes de remover. Para remover, use df.drop_duplicates()</li>
    <li>Os valores nulos de colunas de valores numéricos, devem ser preenchidos com a média da coluna</li>
    <li>Os valores nulos de colunas categóricas, devem ser preenchidas como "desconhecido"</li>
    <li>'Capitalize' colunas com valores categóricos (Não é o caso deste dataframe)</li>
    <li>Retirar símbolo de moedas de colunas com valores monetários, vírgulas ou pontos.</li>    
    <li>Usar map para colunas de datas aonde alguns valores possuem "-", em vez de "/", formatação numérica (Não é o caso deste dataframe)</li>
    <li>Usar map para colunas de diferentes valores booleanos como Yes, No, 1,0, etc... para true ou false. Exemplo abaixo. (Não é o caso deste dataset)
    <img src="boolean_substitutions.jpg"/>
    </li>
    <li>Usar map para normalizar valores de colunas que possuem nomes de países. Exemplo abaixo! (Não é o caso deste dataset) <img src="image.png"/>   
    </li>
    <li>Desconfie de colunas do tipo object</li>
    <li>Utilize a lógica para outros tipos de colunas. Ex: coluna de quantidade com valores negativos</li>
</ul>

Cheque a quantidade de duplicatas antes de remover. Para remover, use df.drop_duplicates()

In [9]:
df_train.duplicated().sum()

np.int64(0)

Os valores nulos de colunas de valores numéricos, devem ser preenchidos com a média da coluna

In [10]:
missing = df_train.isnull().sum()
missing[missing>0]

age         177
embarked      2
dtype: int64

Os valores nulos de colunas categóricas, devem ser preenchidas como "desconhecido

In [11]:
df_copy = df_train.copy()

df_train['age'] = df_train['age'].fillna(df_train['age'].mean())
df_train['embarked'] = df_train['embarked'].fillna('Unknown')
df_train

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,Q

Padronizando algumas colunas

In [12]:
from pandas import to_numeric


df_train['sex'] = (
                    df_train['sex'].
                    str.lower().
                    str.strip()
                  )

df_train['age'] = df_train['age'].astype(float).round(2) 
df_train

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.7,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

Retirar símbolo de moedas de colunas com valores monetários, vírgulas ou pontos.

In [13]:
df_train['fare'] = (
                      df_train['fare'].
                      astype(str).replace('$','').
                      str.replace(',','.').
                      str.strip()
                    ) 

df_train['fare'] = to_numeric(df_train['fare'],errors='coerce') # errors='coerce' ignora os erros
df_train

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.7,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

Desconfie de colunas do tipo object - Ticket é aleatória

In [14]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   passengerid  891 non-null    int64
 1   survived     891 non-null    int64
 2   pclass       891 non-null    int64
 3   name         891 non-null    object
 4   sex          891 non-null    object
 5   age          891 non-null    float64
 6   sibsp        891 non-null    int64
 7   parch        891 non-null    int64
 8   ticket       891 non-null    object
 9   fare         891 non-null    float64
 10  embarked     891 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB

In [15]:
df_train['name'] = (
                    df_train['name'].
                    str.strip().
                    str.capitalize()
                  )

print('Busca por linhas que contenham somente números nas colunas abaixo:')
for col in ['name','sex','embarked']:
    print("Coluna: ",col, " - Qtd: " ,df_train[col].str.isdigit().sum())

Busca por linhas que contenham somente números nas colunas abaixo:
Coluna:  name  - Qtd:  0
Coluna:  sex  - Qtd:  0
Coluna:  embarked  - Qtd:  0

### <center><b>DATAFRAME DE TESTE</b></center>

### <b>ANÁLISE DOS DADOS</b>

In [16]:
df_test.head(10)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
5,897,3,"Svensson, Mr. Johan Cervin",male,14.0,0,0,7538,9.2250,NaN,S
6,898,3,"Connolly, Miss. Kate",female,30.0,0,0,330972,7.6292,NaN,Q
7,899,2,"Caldwell, Mr. Albert Francis",male,26.0,1,1,248738,29.0000,NaN,S
8,900,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,0,2657,7.2292,NaN,C
9,901,3,"Davies, Mr. John Samuel",male,21.0,2,0,A/4 48871,24.1500,NaN,S

In [17]:
df_test.tail(10)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
408,1300,3,"Riordan, Miss. Johanna Hannah""""",female,NaN,0,0,334915,7.7208,NaN,Q
409,1301,3,"Peacock, Miss. Treasteall",female,3.0,1,1,SOTON/O.Q. 3101315,13.7750,NaN,S
410,1302,3,"Naughton, Miss. Hannah",female,NaN,0,0,365237,7.7500,NaN,Q
411,1303,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
412,1304,3,"Henriksson, Miss. Jenny Lovisa",female,28.0,0,0,347086,7.7750,NaN,S
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

### <b>DATA CLEANING</b>

<ul>
    <li><b>Detectando valores faltantes, tipos de dados, quantidade de linhas e colunas</b></li>
    <li><b>Normalizando os nomes das colunas</b></li>
    <li><b>Porcentagem de valores nulos</b></li>
    <li><b>Lidando com duplicatas, valores nulos e colunas bagunçadas (Padronizar colunas com valores categóricos)</b></li>
</ul>

<ul><ul>
    <li>Cheque a quantidade de duplicatas antes de remover. Para remover, use df.drop_duplicates()</li>
    <li>Os valores nulos de colunas de valores numéricos, devem ser preenchidos com a média da coluna</li>
    <li>Os valores nulos de colunas categóricas, devem ser preenchidas como "desconhecido"</li>
    <li>'Capitalize' colunas com valores categóricos (Não é o caso deste dataframe)</li>
    <li>Retirar símbolo de moedas de colunas com valores monetários, vírgulas ou pontos.</li>    
    <li>Desconfie de colunas do tipo object</li>
    <li>Utilize a lógica para outros tipos de colunas. Ex: coluna de quantidade com valores negativos</li>
</ul></ul>

<b>Detectando valores faltantes, tipos de dados, quantidade de linhas e colunas</b>

In [18]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.1+ KB

<b>Normalizando os nomes das colunas</b>

In [19]:
df_test.columns = (
                    df_test.columns.
                    str.strip().
                    str.lower().
                    str.replace(' ','_')
                 )
df_test.columns

Index(['passengerid', 'pclass', 'name', 'sex', 'age', 'sibsp', 'parch',
       'ticket', 'fare', 'cabin', 'embarked'],
      dtype='object')

<b>Porcentagem de valores nulos</b>

In [20]:
missing = df_test.isnull().sum()
missing = missing[missing>0]
missing

age       86
fare       1
cabin    327
dtype: int64

In [21]:
percentage = ((missing / len(df_test)) * 100).round(2)
percentage

age      20.57
fare      0.24
cabin    78.23
dtype: float64

Desprezando a coluna cabin, pois ela possui muitos valores nulos

In [22]:
df_test = df_test.drop(columns=['cabin'],errors='ignore')
df_test

,passengerid,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,S
...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,C

<b>Lidando com duplicatas, valores nulos e colunas bagunçadas (Padronizar colunas com valores categóricos)</b>

Cheque a quantidade de duplicatas antes de remover.

In [23]:
df_test.duplicated().sum()

np.int64(0)

Os valores nulos de colunas de valores numéricos, devem ser preenchidos com a média da coluna

In [24]:
# age, fare
df_test['age'] = df_test['age'].fillna(df_test['age'].mean())
df_test['fare'] = df_test['fare'].fillna(df_test['fare'].mean())
df_test

,passengerid,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked
0,892,3,"Kelly, Mr. James",male,34.50000,0,0,330911,7.8292,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.00000,1,0,363272,7.0000,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.00000,0,0,240276,9.6875,Q
3,895,3,"Wirz, Mr. Albert",male,27.00000,0,0,315154,8.6625,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.00000,1,1,3101298,12.2875,S
...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,30.27259,0,0,A.5. 3236,8.0500,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.00000,0,0,PC 17758,108.9000,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.50000,0,0,SOTON/O.Q. 3101262,7.2500,S
416,1308,3,"Ware, Mr. Frederick",male,30.27259,0,0,359309,8.0500,S
417,1309,3,"Peter, Master. Michael J",male,30.27259,1,1,2668,22.3583,C

Retirar símbolo de moedas de colunas com valores monetários, vírgulas ou pontos.

In [25]:
df_test['fare'] = (
                      df_test['fare'].
                      round(2).
                      astype(str).
                      replace('$','').
                      str.replace(',','.').
                      str.strip()
                   )

df_test['fare'] = to_numeric(df_test['fare'],errors='coerce')
df_test

,passengerid,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked
0,892,3,"Kelly, Mr. James",male,34.50000,0,0,330911,7.83,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.00000,1,0,363272,7.00,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.00000,0,0,240276,9.69,Q
3,895,3,"Wirz, Mr. Albert",male,27.00000,0,0,315154,8.66,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.00000,1,1,3101298,12.29,S
...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,30.27259,0,0,A.5. 3236,8.05,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.00000,0,0,PC 17758,108.90,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.50000,0,0,SOTON/O.Q. 3101262,7.25,S
416,1308,3,"Ware, Mr. Frederick",male,30.27259,0,0,359309,8.05,S
417,1309,3,"Peter, Master. Michael J",male,30.27259,1,1,2668,22.36,C

Desconfie de colunas do tipo object - Ticket é aleatória

In [26]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   passengerid  418 non-null    int64
 1   pclass       418 non-null    int64
 2   name         418 non-null    object
 3   sex          418 non-null    object
 4   age          418 non-null    float64
 5   sibsp        418 non-null    int64
 6   parch        418 non-null    int64
 7   ticket       418 non-null    object
 8   fare         418 non-null    float64
 9   embarked     418 non-null    object
dtypes: float64(2), int64(4), object(4)
memory usage: 32.8+ KB

In [27]:
df_test['name'] = (
                    df_test['name'].
                    str.strip().
                    str.capitalize()
                  )

print('Busca por linhas que contenham somente números nas colunas abaixo:')
for col in ['name','sex','embarked']:
    print("Coluna: ",col, " - Qtd: " ,df_test[col].str.isdigit().sum())

Busca por linhas que contenham somente números nas colunas abaixo:
Coluna:  name  - Qtd:  0
Coluna:  sex  - Qtd:  0
Coluna:  embarked  - Qtd:  0

### <center><b>ANÁLISE EXPLORATÓRIA NO DATAFRAME DE TREINAMENTO</b></center>

In [28]:
df_train.describe()

,passengerid,survived,pclass,age,sibsp,parch,fare
count,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699293,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,13.002015,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,22.000000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,29.700000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,35.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200